### ISSUE TITLE
cannot load such file -- ci/reporter/core (LoadError)

### ISSUE THREAD

**Issue by cciollaro** [alphasights/crawl#2]
I'm checking out this gem to test out my app in development. So far it's great, I just ran into one hiccup during installation: I ran `gem install crawl` and then attempted to `crawl http://localhost:3000 --connections=1 --start=/ --verbose`. I got "cannot load such file -- ci/reporter/core (LoadError)".

Once I ran `gem install ci_reporter` it was fixed. So should "ci_reporter" be in the gemspec?

**Comment by toreriklinnerud** [comment]
Good catch, I don't think it is used, so removing it https://github.com/alphasights/crawl/pull/5
